# Generated by Django 3.2.5 on 2021-12-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
